### ISSUE TITLE
No requirements.txt file to install with

### ISSUE THREAD

**Issue by Wissotsky** [harrisonvanderbyl/rwkv_chatbot#1]
Makes it very tedious to install as you have to look for the necessary libraries yourself or via trial and error.

Also the readme file instructs to run `run.py` which doesnt exist (Guessing you meant `rwkv-run.py` instead)

**Comment by harrisonvanderbyl** [comment]
I did some updates :)
some of the export options and runtimes may require some specifics, but theres no need for them to be installed with everything else
