### ISSUE TITLE
I could start it with Colab. But it keeps talking to itself and I can't talk to it.

### ISSUE THREAD

**Issue by miracle777** [harrisonvanderbyl/rwkv_chatbot#2]
Using Google Colab, I was able to activate it.
I was able to find a study model with 12 GB of RAM available.

But as you can see in the attached picture, it is alone all the time and keeps talking.

How can I chat with it?

Also, what is the prompt for an example?

Then, as shown in the picture, when multiple training models are placed, they are listed but do not seem to be selectable when typing.

Then I tried to run a website with ngrok.
I ran runWebsite.py, but it did not work.
Would it be better to try it on a computer?
Also, if I run on a computer, can I use localhost:3000?
rwkv_chatbot/web-interface/README.md
file.

![スクリーンショット_20230124_131309](https://user-images.githubusercontent.com/13194391/214216475-b430a94c-a3f7-461e-b260-8dd576342db4.png)
![スクリーンショット_20230124_133659](https://user-images.githubusercontent.com/13194391/214216487-c9bb2a55-af04-4f50-8fd2-7181f5d62cde.png)

![スクリーンショット_20230124_133917](https://user-images.githubusercontent.com/13194391/214216495-b5f49a3b-dee3-4d5d-8abf-ff98bf091da3.png)
![スクリーンショット_20230124_135917](https://user-images.githubusercontent.com/13194391/214216523-a83f4afa-c503-4cf1-8b37-bd414e2fb023.png)

**Comment by harrisonvanderbyl** [comment]
Oh hey,please use ./multi.py as the endpoint to start the web interface/discord bot.
I will update the readme shortly

**Comment by miracle777** [comment]
Thank you for letting us know.
